### ISSUE TITLE
Image Database

### ISSUE THREAD

**Issue by iwu78** [trevorhuang1/fte-backend#3]
- [x] Use jsquery to setup table on new page to display uploaded images
- [x] Setup fetch request to get rows in database
- [x] Add a save image to database button and function on prior two pages, setup fetch request to add rows to database

**Comment by liangkyle08** [comment]
### Got query to work for the database (need to add formatting)
![image](https://github.com/trevorhuang1/fte-backend/assets/90527109/c6e2c48f-e541-4ad7-822a-5aae607dd11f)

**Comment by liangkyle08** [comment]
### Got add image to work
![image](https://github.com/trevorhuang1/fte-backend/assets/90527109/6ecf2023-c6d6-451a-9575-6fa160fbc4e1)
![image](https://github.com/trevorhuang1/fte-backend/assets/90527109/399d8e22-9a1c-4954-a476-407d271e4b74)
